name: bitcoin

services:
  bitcoin-external:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}:external-mode
    pull_policy: never
    environment:
      CHAIN: ${BITCOIN_CHAIN}
      MODE: external
      RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      RPC_USERNAME: ${BITCOIN_RPC_USERNAME}
      WEBHOOK_ENDPOINT: ${BITCOIN_WEBHOOK_ENDPOINT}
    networks:
      default:
      internal:
    volumes:
      - /var/bitcoin
      - mega-nfs:/mnt/nfs
    depends_on:
      mega-nfs:
        condition: service_healthy
    stop_grace_period: 5m
    restart: unless-stopped

  bitcoin-internal:
    extends:
      service: bitcoin-external
    image: ${COMPOSE_PROJECT_NAME}:internal-mode
    environment:
      EXTERNAL_PEER: bitcoin-external
      MODE: internal
    networks:
      internal:
        aliases:
          - bitcoin
    depends_on:
      bitcoin-external:
        condition: service_started

  mega-nfs:
    image: ghcr.io/nedix/mega-nfs-docker:v0.0.2
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      EMAIL: ${MEGA_NFS_EMAIL}
      PASSWORD: ${MEGA_NFS_PASSWORD}
      DIRECTORY: ${MEGA_NFS_DIRECTORY}
      BUFFER_SIZE: 64
    networks:
      default:
      internal:
    volumes:
      - /sys/fs/cgroup/mega-nfs:/sys/fs/cgroup
    ports:
      - ${FORWARD_MEGA_NFS_PORT}:2049
    restart: unless-stopped

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
  internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
    internal: true

volumes:
  bitcoin:
  mega-nfs:
    driver_opts:
      type: nfs
      o: 'vers=4,addr=localhost,port=${FORWARD_MEGA_NFS_PORT},rw'
      device: ':/'
