version: '3.9'

services:
  bitcoin-light:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      target: light-mode
    image: ${COMPOSE_PROJECT_NAME}:light-mode
    pull_policy: never
    environment:
      CHAIN: ${BITCOIN_CHAIN}
      CONNECT_PEER: bitcoin-full
      RPC_USERNAME: ${BITCOIN_RPC_USERNAME}
      RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      WEBHOOK_ENDPOINT: http://app/webhook/bitcoin
    networks:
      internal:
        aliases:
          - bitcoin
    ports:
      - ${FORWARD_BITCOIN_RPC_PORT}:8332
    volumes:
      - /var/bitcoin
      - s3-nfs:/mnt/nfs
    depends_on:
      bitcoin-full:
        condition: service_started
      s3-nfs:
        condition: service_healthy
    deploy:
      replicas: 2
    stop_grace_period: 5m
    restart: unless-stopped

  bitcoin-full:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      target: full-mode
    image: ${COMPOSE_PROJECT_NAME}:full-mode
    pull_policy: never
    environment:
      CHAIN: ${BITCOIN_CHAIN}
      RPC_USERNAME: ${BITCOIN_RPC_USERNAME}
      RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      WEBHOOK_ENDPOINT: ${WEBHOOK_ENDPOINT:-http://api/webhook/bitcoin}
    networks:
      default:
      internal:
    volumes:
      - /var/bitcoin
      - s3-nfs:/mnt/nfs
    depends_on:
      s3-nfs:
        condition: service_healthy
    stop_grace_period: 5m
    restart: unless-stopped

  s3-nfs:
    image: ghcr.io/nedix/s3-nfs-docker:1.0.4
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      S3_NFS_BUCKET: ${BITCOIN_S3_BUCKET}
      S3_NFS_ENDPOINT: ${BITCOIN_S3_ENDPOINT}
      S3_NFS_ACCESS_KEY_ID: ${BITCOIN_S3_ACCESS_KEY_ID}
      S3_NFS_SECRET_ACCESS_KEY: ${BITCOIN_S3_SECRET_ACCESS_KEY}
    networks:
      default:
      internal:
    ports:
      - ${FORWARD_BITCOIN_NFS_PORT}:2049
    depends_on:
      minio:
        condition: service_healthy
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    entrypoint: sh
    command: -c 'minio server --console-address ":8900" /data/minio'
    environment:
      MINIO_BUCKET: ${BITCOIN_S3_BUCKET}
      MINIO_ROOT_USER: ${BITCOIN_S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${BITCOIN_S3_SECRET_ACCESS_KEY}
    networks:
      default:
      internal:
    ports:
      - ${FORWARD_MINIO_CONSOLE_PORT}:8900
    volumes:
      - minio:/data/minio
    healthcheck:
      test: [CMD, mc, ready, local]
      retries: 3
      timeout: 5s
    restart: unless-stopped

networks:
  default:
  internal:
    internal: true

volumes:
  bitcoin:
  minio:
  s3-nfs:
    driver_opts:
      type: nfs
      o: 'vers=4,addr=localhost,port=${FORWARD_BITCOIN_NFS_PORT},rw'
      device: ':/'
