name: bitcoin

services:
  bitcoin-external:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      target: external-mode
    image: ${COMPOSE_PROJECT_NAME}:external-mode
    pull_policy: never
    environment:
      CHAIN: ${BITCOIN_CHAIN}
      RPC_USERNAME: ${BITCOIN_RPC_USERNAME}
      RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      WEBHOOK_ENDPOINT: ${WEBHOOK_ENDPOINT}
    networks:
      default:
      internal:
    volumes:
      - /var/bitcoin
      - s3-nfs:/mnt/nfs
    depends_on:
      s3-nfs:
        condition: service_healthy
    stop_grace_period: 5m
    restart: unless-stopped

  bitcoin-internal:
    extends:
      service: bitcoin-external
    build:
      target: internal-mode
    image: ${COMPOSE_PROJECT_NAME}:internal-mode
    environment:
      EXTERNAL_PEER: bitcoin-external
    networks:
      internal:
        aliases:
          - bitcoin
    depends_on:
      bitcoin-external:
        condition: service_started

  s3-nfs:
    image: ghcr.io/nedix/s3-nfs-docker:1.0.4
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse:rwm
    environment:
      S3_NFS_BUCKET: ${S3_BUCKET}
      S3_NFS_ENDPOINT: ${S3_ENDPOINT}
      S3_NFS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_NFS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    networks:
      default:
      internal:
    ports:
      - ${FORWARD_S3_NFS_PORT}:2049
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    entrypoint: sh
    command: -c 'minio server --console-address ":8900" /data/minio'
    environment:
      MINIO_BUCKET: ${S3_BUCKET}
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    networks:
      default:
      internal:
    ports:
      - ${FORWARD_MINIO_CONSOLE_PORT}:8900
    volumes:
      - minio:/data/minio
    healthcheck:
      test: [CMD, mc, ready, local]
      retries: 3
      timeout: 5s
    restart: unless-stopped
    deploy:
      replicas: 0

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
  internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
    internal: true

volumes:
  bitcoin:
  minio:
  s3-nfs:
    driver_opts:
      type: nfs
      o: 'vers=4,addr=localhost,port=${FORWARD_S3_NFS_PORT},rw'
      device: ':/'
