name: bitcoin-test

services:
  test:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      target: test
    networks:
      default:
      internal:
    depends_on:
      bitcoin-external:
        condition: service_started
      bitcoin-internal:
        condition: service_started
    deploy:
      replicas:
        0

  bitcoin-external:
    extends:
      file: docker-compose.yml
      service: bitcoin-external

  bitcoin-internal:
    extends:
      file: docker-compose.yml
      service: bitcoin-internal

  s3-nfs:
    extends:
      file: docker-compose.yml
      service: s3-nfs
    depends_on:
      minio:
        condition: service_healthy

  minio:
    extends:
      file: docker-compose.yml
      service: minio
    deploy:
      replicas: 1

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
  internal:
    name: ${COMPOSE_PROJECT_NAME}-internal
    internal: true

volumes:
  bitcoin:
  minio:
  s3-nfs:
    driver_opts:
      type: nfs
      o: 'vers=4,addr=localhost,port=${FORWARD_S3_NFS_PORT},rw'
      device: ':/'
