#!/usr/bin/env sh

if echo "$(cat /var/log/bitcoin/current && cat /var/log/bitcoin/*.s 2> /dev/null)" | grep -q \
    -e "Errors in block header" \
; then
    rm $(ls -Art /var/bitcoin/blocks/ | tail -n1)
fi
