name: Pull request merged

on:
  merge_group:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  workflow_call:
    inputs:
      workflow_call:
        type: boolean
        default: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check labels
        if: contains(github.event.pull_request.labels.*.name, 'workflows')
        run: exit 1

      - name: Check merged or called
        if: github.event.pull_request.merged != true && inputs.workflow_call != true
        run: exit 1

  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Bump version
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  update-package:
    name: Update package
    needs:
      - bump-version
    uses: ./.github/workflows/update-package.yaml
